In [1]:
import pandas as pd 
import numpy as np

In [2]:
numpy.array([1,2,3])

array([1, 2, 3])

In [3]:
numpy.array([(1,2,3),(3,4,5)])

array([[1, 2, 3],
       [3, 4, 5]])

In [4]:
numpy.array([1,2,3,4],[2,3,3])

TypeError: data type not understood

In [7]:
numpy.array([[(1,2,3,4),(2,3,3,3)],[(2,3,3,4),(3,4,5,6)]])

array([[[1, 2, 3, 4],
        [2, 3, 3, 3]],

       [[2, 3, 3, 4],
        [3, 4, 5, 6]]])

In [8]:
np.zeros((3,4))

NameError: name 'np' is not defined